using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MongoDB.Driver;
using BackendService.Data;
using BackendService.Models.Entities;

namespace BackendService.Controllers
{
    [ApiController]
    [Route("api/admin")]
    [Authorize(Roles = "Admin")]
    public class AdminQuizController : ControllerBase
    {
        private readonly MongoDbContext _context;

        public AdminQuizController(MongoDbContext context)
        {
            _context = context;
        }

        // --- Quiz Management ---
        [HttpGet("quizzes")]
        public async Task<ActionResult<IEnumerable<CareerQuiz>>> GetAllQuizzes()
        {
            return Ok(await _context.CareerQuizzes.Find(_ => true).ToListAsync());
        }

        [HttpGet("quizzes/{id}")]
        public async Task<ActionResult<CareerQuiz>> GetQuizById(string id)
        {
            var quiz = await _context.CareerQuizzes.Find(q => q.Id == id).FirstOrDefaultAsync();
            if (quiz == null) return NotFound();
            return Ok(quiz);
        }

        [HttpPost("quizzes")]
        public async Task<ActionResult<CareerQuiz>> CreateQuiz([FromBody] CareerQuiz quiz)
        {
            quiz.Id = null; // Ensure ID is generated by MongoDB
            await _context.CareerQuizzes.InsertOneAsync(quiz);
            return Ok(quiz);
        }

        [HttpPut("quizzes/{id}")]
        public async Task<IActionResult> UpdateQuiz(string id, [FromBody] CareerQuiz quiz)
        {
            var result = await _context.CareerQuizzes.ReplaceOneAsync(q => q.Id == id, quiz);
            if (result.MatchedCount == 0) return NotFound();
            return Ok(quiz);
        }

        [HttpDelete("quizzes/{id}")]
        public async Task<IActionResult> DeleteQuiz(string id)
        {
            var result = await _context.CareerQuizzes.DeleteOneAsync(q => q.Id == id);
            if (result.DeletedCount == 0) return NotFound();
            return Ok(new { message = "Xóa bài khảo sát thành công." });
        }

        // --- Question Management ---
        [HttpGet("questions")]
        public async Task<ActionResult<IEnumerable<CareerQuestion>>> GetAllQuestions()
        {
            return Ok(await _context.CareerQuestions.Find(_ => true).ToListAsync());
        }

        [HttpGet("questions/{id}")]
        public async Task<ActionResult<CareerQuestion>> GetQuestionById(string id)
        {
            var question = await _context.CareerQuestions.Find(q => q.Id == id).FirstOrDefaultAsync();
            if (question == null) return NotFound();
            return Ok(question);
        }

        [HttpPost("questions")]
        public async Task<ActionResult<CareerQuestion>> CreateQuestion([FromBody] CareerQuestion question)
        {
            question.Id = null;
            await _context.CareerQuestions.InsertOneAsync(question);
            return Ok(question);
        }

        [HttpPut("questions/{id}")]
        public async Task<IActionResult> UpdateQuestion(string id, [FromBody] CareerQuestion question)
        {
            var result = await _context.CareerQuestions.ReplaceOneAsync(q => q.Id == id, question);
            if (result.MatchedCount == 0) return NotFound();
            return Ok(question);
        }

        [HttpDelete("questions/{id}")]
        public async Task<IActionResult> DeleteQuestion(string id)
        {
            var result = await _context.CareerQuestions.DeleteOneAsync(q => q.Id == id);
            if (result.DeletedCount == 0) return NotFound();
            return Ok(new { message = "Xóa câu hỏi thành công." });
        }
    }
}
